version: "3.8"

services:
  backend:
    build: ./server
    ports:
      - "8080:8080"
    environment:
      - REDIS_URI=${REDIS_URI}
      - MONGO_URI=${MONGO_URI}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - JDOODLE_CLIENT_ID=${JDOODLE_CLIENT_ID}
      - JDOODLE_CLIENT_SECRET=${JDOODLE_CLIENT_SECRET}
  frontend:
    build: ./client
    ports:
      - "5173:5173"
